name: colornote
description: Samsung-Notes-style note app with saved color palette and exports.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_colorpicker: ^1.1.0
  archive: ^3.6.1
  path_provider: ^2.1.3
  share_plus: ^9.0.0

flutter:
  uses-material-design: true
